"""
In-memory data store for local development (no database needed).
In production, replace with Firestore or PostgreSQL.
"""
from datetime import datetime
from typing import Dict, List, Optional
import uuid

# ---- PRODUCTS DATA ----
PRODUCTS: List[Dict] = [
    {
        "id": "prod-001",
        "name": "Crimson Anarkali Suit",
        "slug": "crimson-anarkali-suit",
        "description": "A stunning crimson red anarkali suit crafted from premium georgette fabric. Adorned with intricate gold zari embroidery along the hem and sleeves. Perfect for weddings and festive occasions. Comes with matching churidar and dupatta.",
        "price": 4999,
        "compare_price": 7499,
        "category": "anarkali",
        "subcategory": "festive",
        "fabric": "Georgette",
        "care": "Dry clean only",
        "tags": ["anarkali", "festive", "wedding", "embroidered"],
        "images": [
            {"url": "https://images.unsplash.com/photo-1614886137799-8f3dc0a498bd?w=800&q=80", "alt": "Crimson Anarkali Suit"},
            {"url": "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=800&q=80", "alt": "Crimson Anarkali Suit Back"},
        ],
        "variants": [
            {"size": "XS", "stock": 3}, {"size": "S", "stock": 5},
            {"size": "M", "stock": 8}, {"size": "L", "stock": 6},
            {"size": "XL", "stock": 4}, {"size": "XXL", "stock": 2},
        ],
        "is_featured": True, "is_new": True, "is_bestseller": False,
        "rating": 4.8, "review_count": 124, "created_at": datetime.now().isoformat(),
    },
    {
        "id": "prod-002",
        "name": "Ivory Silk Kurti Set",
        "slug": "ivory-silk-kurti-set",
        "description": "Elegant ivory pure silk kurti with delicate hand-block printing. Paired with matching palazzo pants and organza dupatta. The subtle floral motifs add a touch of royalty to this ensemble.",
        "price": 3499,
        "compare_price": 5500,
        "category": "kurti-set",
        "subcategory": "daily-wear",
        "fabric": "Pure Silk",
        "care": "Hand wash cold",
        "tags": ["kurti", "silk", "ethnic", "daily-wear"],
        "images": [
            {"url": "https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=800&q=80", "alt": "Ivory Silk Kurti"},
            {"url": "https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=800&q=80", "alt": "Ivory Silk Kurti Set"},
        ],
        "variants": [
            {"size": "S", "stock": 10}, {"size": "M", "stock": 12},
            {"size": "L", "stock": 9}, {"size": "XL", "stock": 5},
        ],
        "is_featured": True, "is_new": False, "is_bestseller": True,
        "rating": 4.6, "review_count": 89, "created_at": datetime.now().isoformat(),
    },
    {
        "id": "prod-003",
        "name": "Saffron Embroidered Anarkali",
        "slug": "saffron-embroidered-anarkali",
        "description": "Vibrant saffron anarkali with heavy chikankari embroidery on pure mul cotton. The flowing silhouette and intricate needlework make it ideal for festive celebrations and cultural events.",
        "price": 5999,
        "compare_price": 8999,
        "category": "anarkali",
        "subcategory": "festive",
        "fabric": "Mul Cotton",
        "care": "Gentle machine wash",
        "tags": ["anarkali", "chikankari", "festive", "cotton"],
        "images": [
            {"url": "https://images.unsplash.com/photo-1631233859484-4fdf47e57fa8?w=800&q=80", "alt": "Saffron Anarkali"},
            {"url": "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=800&q=80", "alt": "Saffron Anarkali Detail"},
        ],
        "variants": [
            {"size": "XS", "stock": 2}, {"size": "S", "stock": 7},
            {"size": "M", "stock": 10}, {"size": "L", "stock": 8},
            {"size": "XL", "stock": 3},
        ],
        "is_featured": True, "is_new": True, "is_bestseller": True,
        "rating": 4.9, "review_count": 201, "created_at": datetime.now().isoformat(),
    },
    {
        "id": "prod-004",
        "name": "Peacock Blue Kurti Dupatta",
        "slug": "peacock-blue-kurti-dupatta",
        "description": "Mesmerizing peacock blue kurti in premium chanderi silk with gold gota patti border. Comes with matching chiffon dupatta with tassels. A perfect blend of tradition and contemporary style.",
        "price": 2799,
        "compare_price": 4200,
        "category": "kurti-dupatta",
        "subcategory": "casual",
        "fabric": "Chanderi Silk",
        "care": "Dry clean recommended",
        "tags": ["kurti", "chanderi", "dupatta", "casual", "festive"],
        "images": [
            {"url": "https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=800&q=80", "alt": "Peacock Blue Kurti"},
            {"url": "https://images.unsplash.com/photo-1554412933-514a83d2f3c8?w=800&q=80", "alt": "Peacock Blue Kurti Dupatta"},
        ],
        "variants": [
            {"size": "S", "stock": 8}, {"size": "M", "stock": 15},
            {"size": "L", "stock": 12}, {"size": "XL", "stock": 6}, {"size": "XXL", "stock": 3},
        ],
        "is_featured": False, "is_new": True, "is_bestseller": False,
        "rating": 4.5, "review_count": 67, "created_at": datetime.now().isoformat(),
    },
    {
        "id": "prod-005",
        "name": "Forest Green Co-ord Set",
        "slug": "forest-green-coord-set",
        "description": "Chic forest green co-ord set featuring a short kurta and wide-leg palazzo. Made from breathable linen blend fabric with delicate thread embroidery at the neckline. Perfect for brunch, office or casual outings.",
        "price": 3199,
        "compare_price": 4800,
        "category": "co-ord-set",
        "subcategory": "casual",
        "fabric": "Linen Blend",
        "care": "Machine wash cold",
        "tags": ["coord-set", "linen", "casual", "modern"],
        "images": [
            {"url": "https://images.unsplash.com/photo-1585487000160-6ebcfceb0d03?w=800&q=80", "alt": "Forest Green Co-ord Set"},
            {"url": "https://images.unsplash.com/photo-1576185850227-1f72b7f8d48e?w=800&q=80", "alt": "Forest Green Co-ord Set Detail"},
        ],
        "variants": [
            {"size": "XS", "stock": 5}, {"size": "S", "stock": 9},
            {"size": "M", "stock": 14}, {"size": "L", "stock": 10}, {"size": "XL", "stock": 4},
        ],
        "is_featured": False, "is_new": True, "is_bestseller": False,
        "rating": 4.4, "review_count": 43, "created_at": datetime.now().isoformat(),
    },
    {
        "id": "prod-006",
        "name": "Royal Purple Half Saree",
        "slug": "royal-purple-half-saree",
        "description": "Exquisite royal purple half saree set with kanjeevaram silk skirt, matching blouse and contrast zari border. The traditional South Indian half saree design is elevated with contemporary draping. A stunning choice for Bharatanatyam, puberty ceremonies and cultural programs.",
        "price": 8999,
        "compare_price": 12500,
        "category": "half-saree",
        "subcategory": "festive",
        "fabric": "Kanjeevaram Silk",
        "care": "Professional dry clean only",
        "tags": ["half-saree", "silk", "south-indian", "festive", "wedding"],
        "images": [
            {"url": "https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=800&q=80", "alt": "Royal Purple Half Saree"},
            {"url": "https://images.unsplash.com/photo-1614886137799-8f3dc0a498bd?w=800&q=80", "alt": "Half Saree Detail"},
        ],
        "variants": [
            {"size": "S", "stock": 4}, {"size": "M", "stock": 6},
            {"size": "L", "stock": 5}, {"size": "XL", "stock": 3},
        ],
        "is_featured": True, "is_new": False, "is_bestseller": True,
        "rating": 4.9, "review_count": 312, "created_at": datetime.now().isoformat(),
    },
    {
        "id": "prod-007",
        "name": "Dusty Rose Ethnic Maxi",
        "slug": "dusty-rose-ethnic-maxi",
        "description": "Romantic dusty rose ethnic maxi dress with delicate floral print. Features a flattering A-line silhouette, smocked waist and ruffle hem. The lightweight rayon fabric makes it comfortable for all-day wear.",
        "price": 2499,
        "compare_price": 3800,
        "category": "ethnic-maxi",
        "subcategory": "casual",
        "fabric": "Rayon",
        "care": "Machine wash cold, do not tumble dry",
        "tags": ["maxi", "ethnic", "casual", "floral", "summer"],
        "images": [
            {"url": "https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=800&q=80", "alt": "Dusty Rose Maxi"},
            {"url": "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800&q=80", "alt": "Dusty Rose Maxi Detail"},
        ],
        "variants": [
            {"size": "XS", "stock": 6}, {"size": "S", "stock": 11},
            {"size": "M", "stock": 15}, {"size": "L", "stock": 9}, {"size": "XL", "stock": 5},
        ],
        "is_featured": False, "is_new": False, "is_bestseller": True,
        "rating": 4.7, "review_count": 178, "created_at": datetime.now().isoformat(),
    },
    {
        "id": "prod-008",
        "name": "Midnight Navy Skirt Set",
        "slug": "midnight-navy-skirt-set",
        "description": "Sophisticated midnight navy skirt and top set, featuring a cropped embroidered top and flared skirt with mirror work. The combination of traditional mirror embroidery and modern silhouette creates a perfect fusion look.",
        "price": 3799,
        "compare_price": 5500,
        "category": "skirt-set",
        "subcategory": "festive",
        "fabric": "Crepe",
        "care": "Dry clean recommended",
        "tags": ["skirt", "top", "mirror-work", "fusion", "festive"],
        "images": [
            {"url": "https://images.unsplash.com/photo-1554412933-514a83d2f3c8?w=800&q=80", "alt": "Midnight Navy Skirt Set"},
            {"url": "https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=800&q=80", "alt": "Navy Skirt Set Detail"},
        ],
        "variants": [
            {"size": "S", "stock": 7}, {"size": "M", "stock": 10},
            {"size": "L", "stock": 8}, {"size": "XL", "stock": 4},
        ],
        "is_featured": False, "is_new": True, "is_bestseller": False,
        "rating": 4.3, "review_count": 56, "created_at": datetime.now().isoformat(),
    },
    {
        "id": "prod-009",
        "name": "Terracotta Bandhani Kurti",
        "slug": "terracotta-bandhani-kurti",
        "description": "Authentic terracotta bandhani kurti in soft cotton fabric. The traditional tie-dye technique creates stunning patterns that are unique to each piece. Lightweight and comfortable, this kurti is perfect for summer days.",
        "price": 1899,
        "compare_price": 2800,
        "category": "kurti",
        "subcategory": "daily-wear",
        "fabric": "Cotton",
        "care": "Hand wash in cold water",
        "tags": ["kurti", "bandhani", "cotton", "daily-wear", "traditional"],
        "images": [
            {"url": "https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=800&q=80", "alt": "Terracotta Bandhani Kurti"},
            {"url": "https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=800&q=80", "alt": "Bandhani Pattern Detail"},
        ],
        "variants": [
            {"size": "S", "stock": 12}, {"size": "M", "stock": 18},
            {"size": "L", "stock": 15}, {"size": "XL", "stock": 8}, {"size": "XXL", "stock": 4},
        ],
        "is_featured": False, "is_new": False, "is_bestseller": True,
        "rating": 4.5, "review_count": 234, "created_at": datetime.now().isoformat(),
    },
    {
        "id": "prod-010",
        "name": "Sage Green Lounge Wear Set",
        "slug": "sage-green-lounge-wear-set",
        "description": "Ultra-comfortable sage green lounge wear set featuring a relaxed fit kurta and wide-leg pants. Made from premium modal fabric that feels like a second skin. Perfect for work from home, relaxed evenings and lazy weekends.",
        "price": 2299,
        "compare_price": 3400,
        "category": "lounge",
        "subcategory": "daily-wear",
        "fabric": "Modal",
        "care": "Machine wash gentle",
        "tags": ["lounge", "comfort", "modal", "daily-wear", "work-from-home"],
        "images": [
            {"url": "https://images.unsplash.com/photo-1576185850227-1f72b7f8d48e?w=800&q=80", "alt": "Sage Green Lounge Set"},
            {"url": "https://images.unsplash.com/photo-1585487000160-6ebcfceb0d03?w=800&q=80", "alt": "Lounge Set Detail"},
        ],
        "variants": [
            {"size": "XS", "stock": 8}, {"size": "S", "stock": 14},
            {"size": "M", "stock": 20}, {"size": "L", "stock": 16}, {"size": "XL", "stock": 10},
        ],
        "is_featured": False, "is_new": True, "is_bestseller": False,
        "rating": 4.6, "review_count": 92, "created_at": datetime.now().isoformat(),
    },
    {
        "id": "prod-011",
        "name": "Gold Tissue Anarkali",
        "slug": "gold-tissue-anarkali",
        "description": "Opulent gold tissue anarkali with intricate cutdana and sequin embroidery. The lightweight tissue fabric gives an ethereal, luminous look. Paired with a churidar and matching dupatta with tassel edges.",
        "price": 7499,
        "compare_price": 10999,
        "category": "anarkali",
        "subcategory": "bridal",
        "fabric": "Tissue Silk",
        "care": "Professional dry clean only",
        "tags": ["anarkali", "bridal", "gold", "sequin", "wedding"],
        "images": [
            {"url": "https://images.unsplash.com/photo-1631233859484-4fdf47e57fa8?w=800&q=80", "alt": "Gold Tissue Anarkali"},
            {"url": "https://images.unsplash.com/photo-1614886137799-8f3dc0a498bd?w=800&q=80", "alt": "Gold Anarkali Detail"},
        ],
        "variants": [
            {"size": "XS", "stock": 2}, {"size": "S", "stock": 4},
            {"size": "M", "stock": 5}, {"size": "L", "stock": 3}, {"size": "XL", "stock": 2},
        ],
        "is_featured": True, "is_new": False, "is_bestseller": True,
        "rating": 4.9, "review_count": 156, "created_at": datetime.now().isoformat(),
    },
    {
        "id": "prod-012",
        "name": "Lavender Lawn Suit",
        "slug": "lavender-lawn-suit",
        "description": "Breezy lavender lawn suit with digital floral print. Features a long kurta with pintucks, matching straight pants and chiffon dupatta. The soft pastel palette makes it ideal for daytime events and casual gatherings.",
        "price": 2999,
        "compare_price": 4500,
        "category": "kurti-set",
        "subcategory": "casual",
        "fabric": "Lawn Cotton",
        "care": "Machine wash gentle cycle",
        "tags": ["suit", "lawn", "casual", "floral", "pastel"],
        "images": [
            {"url": "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800&q=80", "alt": "Lavender Lawn Suit"},
            {"url": "https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=800&q=80", "alt": "Lavender Suit Detail"},
        ],
        "variants": [
            {"size": "S", "stock": 9}, {"size": "M", "stock": 14},
            {"size": "L", "stock": 11}, {"size": "XL", "stock": 6}, {"size": "XXL", "stock": 3},
        ],
        "is_featured": False, "is_new": True, "is_bestseller": False,
        "rating": 4.4, "review_count": 73, "created_at": datetime.now().isoformat(),
    },
]

# In-memory storage
USERS: Dict[str, Dict] = {}
CARTS: Dict[str, Dict] = {}
ORDERS: Dict[str, Dict] = {}
WISHLISTS: Dict[str, List[str]] = {}
